[package]
license = "MIT"
name = "music-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
audiotags = "0.5.0"
clap = { version = "4.5.53", features = ["derive", "env"] }
dirs = "6.0.0"
governor = "0.6"
musicbrainz_rs = "0.12.0"
reqwest = { version = "0.12.24", features = ["json"] }
rusqlite = { version = "0.37", features = ["bundled"] }
rusqlite_migration = "2.3.0"
serde = "1.0.228"
serde_json = "1.0.145"
sha2 = "0.10"
tokio = {version = "1.48.0", features = ["full"] }
toml = "0.9.8"
walkdir = "2.5.0"
which = "8.0.0"
soulseek-rs-lib = "0.3.0"
unaccent = "0.1"
regex = { version = "1.10", features = ["unicode-perl"] }
futures = "0.3"
async-trait = "0.1"
ratatui = "0.28"
crossterm = "0.28"
backoff = { version = "0.4.0", features = ["tokio"] }
sea-orm = { version = "2.0.0-rc", features = [ "sqlx-sqlite", "tokio", "macros", "with-json" ] }

[dev-dependencies]
mockall = "0.12"
tokio-test = "0.4"
