services:
  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "6831:6831/udp" # Jaeger agent compact Thrift protocol (UDP)
      - "6832:6832/udp" # Jaeger agent binary Thrift protocol (UDP)
      - "5778:5778" # Jaeger agent HTTP management port
      - "16686:16686" # Jaeger query UI port
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "14250:14250" # Jaeger collector gRPC
      - "14268:14268" # Jaeger collector HTTP (thrift)
      - "14269:14269" # Jaeger collector admin (HTTP)
      - "9411:9411" # Zipkin collector port
